### ISSUE TITLE
cherrypy error

### ISSUE THREAD

**Issue by Bart39** [avjui/Gamez#42]
Traceback (most recent call last):
  File "Gamez.py", line 3, in <module>
    import cherrypy
  File "/Gamez/cherrypy/**init**.py", line 62, in <module>
    from cherrypy._cpcompat import urljoin as _urljoin, urlencode as _urlencode
  File "/Gamez/cherrypy/_cpcompat.py", line 208, in <module>
    from http.cookies import SimpleCookie, CookieError
ImportError: No module named http.cookies

running on python2.7 via pythonbrew on debian squeeze

**Comment by avjui** [comment]
It seem to be a issues of you python version. perhaps you can test a other one
