### ISSUE TITLE
updategamelist gives error

### ISSUE THREAD

**Issue by josh4trunks** [avjui/Gamez#80]
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/pbi/gamez-amd64/share/gamez/Gamez/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/pbi/gamez-amd64/share/gamez/Gamez/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/usr/pbi/gamez-amd64/share/gamez/Gamez/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/usr/pbi/gamez-amd64/share/gamez/Gamez/gamez/WebRoot.py", line 1886, in updategamelist
    AddComingSoonGames()
  File "/usr/pbi/gamez-amd64/share/gamez/Gamez/gamez/DBFunctions.py", line 505, in AddComingSoonGames
    DebugLogEvent(" Release date for " + str(game_name).encode(encoding='UTF-8',errors='strict') + " is " + str(release_date).encode(encoding='UTF-8',errors='strict'))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe6' in position 12: ordinal not in range(128)

**Comment by avjui** [comment]
For dirty fix please deactivate debug log in config
