### ISSUE TITLE
Cannot start Gamez

### ISSUE THREAD

**Issue by Martijn085** [avjui/Gamez#82]
Just updated and when i start gamez i get this error:

Traceback (most recent call last):
  File "/usr/local/gamez/Gamez.py", line 12, in <module>
    import gamez.GameTasks
  File "/usr/local/Gamez/gamez/GameTasks.py", line 6, in <module>
    import requests
ImportError: No module named requests

**Comment by avjui** [comment]
You must install the requests modul
http://docs.python-requests.org/en/latest/
